### ISSUE TITLE
Volumes on Ghost

### ISSUE THREAD

**Issue by Bammede** [bitnami/bitnami-docker-ghost#102]
Cannot use config ghost config files like default ghost docker.
config.production.json have all mysql authentication data etc.

My docker-compose:
rootless installation

```
ghost:
    container_name: ghost
    image: bitnami/ghost:latest
    restart: unless-stopped
    cap_add:
      - NET_BIND_SERVICE  
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      url: https://example.com
    volumes:
      - ./ghostcms/content:/var/lib/ghost/content
      - ./ghostcms/config.production.json:/var/lib/ghost/config.production.json
```
