### ISSUE TITLE
Error connecting yo MySQL Server

### ISSUE THREAD

**Issue by Bluefitdev** [bitnami/bitnami-docker-ghost#104]
Hi Guys,

Sorry if this is a stupid question. But is the image supposed to work with mysql backend? 

I have setup this chart in the GKE with CloudSQL backend that has MySQL db

I have this on my `values.yml`, however the container keep crashing and saying can't connect to MySQL Database.

```
externalDatabase:
  database: db
  port: 3306
  user: user
  password: pass
  host: 12.12.12.12
```

Note that db details has been changed 

CHeers
