### ISSUE TITLE
SMTP email mailgun configuration timed out

### ISSUE THREAD

**Issue by Bluefitdev** [bitnami/bitnami-docker-ghost#105]
Hi there,

has anyone managed to setup email config with k8s? I tried so many things in the `values.yaml` but nothing works. None of the invitation is sent out. We are using the smtp deets from mailgun in our other microservice and it works well..

here's my current setup from `values.yaml`:
```
smtpHost: 'smtp.mailgun.org'
smtpUser: 'postmaster@mydomain.com.au'
smtpPort: 25
smtpPassword: 'my-password'
smtpFromAddress: 'admin@mydomain.com.au'
smtpService: 'Mailgun'
```

I also tried another one with the SMTP_SECURE_CONNECTION in extra env var like this:
```
smtpHost: 'smtp.mailgun.org'
smtpUser: 'postmaster@mydomain.com.au'
smtpPort: 25
smtpPassword: 'my-password'
smtpFromAddress: 'admin@mydomain.com.au'
smtpService: 'Mailgun'
extraEnvVars:
  - name: 'SMTP_SECURE_CONNECTION'
     value: 'true'
```

If i don't put quote on the true value, it returns error too. Mailgun doesn't seem to get any request from my admin site as well. Not sure if this is a bug, but would appreciate some help

Cheers

<img width="919" alt="Screen Shot 2021-03-05 at 9 21 27 am" src="https://user-images.githubusercontent.com/56941349/110038695-31426a00-7d94-11eb-9e06-3661e27a9fd3.png">
