### ISSUE TITLE
Ghost will ignore ghostUsername and ghostPassword on values.yaml when provided with blank existing PVC

### ISSUE THREAD

**Issue by SiegfredRodriguez** [bitnami/bitnami-docker-ghost#106]
Hello, I am currently trying to deploy ghost via Helm, but i have found a strange behavior.

It seems that if i provided existing PVCs it causes the chart to ignore ghostUsername and ghostPassword,
I have tested this on my cluster.

Using existing claim (blank):
- no user with that email

Auto volume allocation:
- Login successful

Is this intended behavior?

I am using existing blank PVC so i can control them better.
is there a work around for this?

```
ghostHost: mysite.com
ghostProtocol: https
ghostPort: 443
ghostEmail: <email>
ghostUsername: <email>
ghostPassword: <password>
allowEmptyPassword: no
replicaCount: 1

persistence:
  existingClaim: ghost-storage-pvc

service:
  type: ClusterIP
  port: 443

mariadb:
  auth:
    rootPassword: <password>
    username: <dbuname>
    password: <password>
  primary:
    persistence:
      existingClaim: ghost-mariadb-pvc
```
