### ISSUE TITLE
Bitnami Ghost docker blocked in startup loop

### ISSUE THREAD

**Issue by papalouf** [bitnami/bitnami-docker-ghost#122]
### Name and Version

bitnami/ghost:latest

### What steps will reproduce the bug?

1- using Portainer (or docker-compose), start a stack with the docker-compose.yml below. 

```yaml
version: '3.8'
services:
  ghost_ptolemaios:
    container_name: 'ghost_ptolemaios'
    image: docker.io/bitnami/ghost:latest
    restart: always
    ports:
      - '12368:2368'
    environment:
      # User/Site configuration
      - GHOST_USERNAME=REDACTED
      - GHOST_PASSWORD=REDACTED
      - GHOST_EMAIL=REDACTED
      - GHOST_BLOG_TITLE=REDACTED
      - GHOST_HOST=REDACTED
      # DB connection configuration 
      - GHOST_DATABASE_HOST=db_ghost_ptolemaios
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_NAME=bitnami_ghost
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_PASSWORD=REDACTED
      # Create a database for Ghost using mysql_client
      # TO USE ONLY FIRST TIME
      - MYSQL_CLIENT_FLAVOR=mariadb
      - MYSQL_CLIENT_DATABASE_HOST=db_ghost_ptolemaios
      - MYSQL_CLIENT_DATABASE_PORT_NUMBER=3306
      - MYSQL_CLIENT_DATABASE_ROOT_USER=root
      - MYSQL_CLIENT_DATABASE_ROOT_PASSWORD=REDACTED
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_ghost
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_ghost
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=REDACTED
      - BITNAMI_DEBUG=true
    depends_on:
      - db_ghost_ptolemaios
    volumes:
      - /var/www/Ghost_Ptolemaios/bitnami:/bitnami
    networks:
      - backend
      - frontend
  db_ghost_ptolemaios:
    container_name: 'db_ghost_ptolemaios'
    image: docker.io/bitnami/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=REDACTED
      - MARIADB_CHARACTER_SET=utf8
      - MARIADB_COLLATE=utf8_general_ci
      - MARIADB_SKIP_TEST_DB=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_PASSWORD=REDACTED  
      - MARIADB_EXTRA_FLAGS=--max-allowed-packet=128M --innodb-log-file-size=64M --max-connect-errors=100000 --max_connections=4000
      - BITNAMI_DEBUG=true
    volumes:
      - /var/www/Ghost_Ptolemaios/bitnami:/bitnami
    networks:
      - backend
networks:
  frontend:
    external: true
    name: Internal
  backend:
    external: false
    name: ghost_ptolemaios_backend
```

2- Both Ghost and MariaDB containers starts

3- Ghost container seems entering in a restart loop

### What is the expected behavior?

Both Ghost and MariaDB containers startup fully and running correctly

### What do you see instead?

Ghost container stucked in a restart loop without explicit logs. 

MariaDB container stuck with 

```
2022-02-17 11:19:15 15 [Warning] Aborted connection 15 to db: 'bitnami_ghost' user: 'bn_ghost' host: '192.168.96.3' (Got an error reading communication packets)
2022-02-17 11:19:15 11 [Warning] Aborted connection 11 to db: 'bitnami_ghost' user: 'bn_ghost' host: '192.168.96.3' (Got an error reading communication packets)
2022-02-17 11:19:15 12 [Warning] Aborted connection 12 to db: 'bitnami_ghost' user: 'bn_ghost' host: '192.168.96.3' (Got an error reading communication packets)
2022-02-17 11:19:15 14 [Warning] Aborted connection 14 to db: 'bitnami_ghost' user: 'bn_ghost' host: '192.168.96.3' (Got an error reading communication packets)
2022-02-17 11:19:15 13 [Warning] Aborted connection 13 to db: 'bitnami_ghost' user: 'bn_ghost' host: '192.168.96.3' (Got an error reading communication packets)
```

Ghost container stuck in a loop at "Starting Ghost in background"

```
ghost 11:40:35.86 INFO  ==> Starting Ghost in background
ghost 11:38:29.35 INFO  ==> Starting Ghost in background
ghost 11:39:31.68 
ghost 11:39:31.69 Welcome to the Bitnami ghost container
ghost 11:39:31.69 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
ghost 11:39:31.69 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
ghost 11:39:31.69 
ghost 11:39:31.69 INFO  ==> Configuring libnss_wrapper
ghost 11:39:31.72 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 11:39:31.72 INFO  ==> Trying to connect to the database server
ghost 11:39:31.72 DEBUG ==> Executing SQL command:
SELECT 1
1
ghost 11:39:31.73 INFO  ==> Creating database user bn_ghost
ghost 11:39:31.73 DEBUG ==> creating database user \'bn_ghost\'
ghost 11:39:31.73 DEBUG ==> Executing SQL command:
create or replace user 'bn_ghost'@'%' identified by "testdemotsdepasse";
ghost 11:39:31.78 DEBUG ==> Removing all other hosts for the user
ghost 11:39:31.78 DEBUG ==> Executing SQL command:
select Host from user where User='bn_ghost' and Host!='%';
ghost 11:39:31.80 DEBUG ==> Creating database bitnami_ghost
ghost 11:39:31.80 INFO  ==> Creating database bitnami_ghost
ghost 11:39:31.81 DEBUG ==> Executing SQL command:
create database if not exists `bitnami_ghost` ;
ghost 11:39:31.83 DEBUG ==> Providing privileges to username bn_ghost on database bitnami_ghost
ghost 11:39:31.84 DEBUG ==> Executing SQL command:
ghost 11:39:31.95 DEBUG ==> Validating settings in GHOST_* environment variables...
grant all on `bitnami_ghost`.* to 'bn_ghost'@'%';
ghost 11:39:31.96 INFO  ==> Ensuring Ghost directories exist
ghost 11:39:31.96 INFO  ==> Trying to connect to the database server
ghost 11:39:31.97 DEBUG ==> Executing SQL command:
ghost 11:39:31.97 INFO  ==> Configuring database
ghost 11:39:31.98 INFO  ==> Setting up Ghost
☱ Inspecting operating system☱ Checking for deprecations✔ Configuring Ghost
Ghost uses direct mail by default. To set up an alternative email method read our docs at https://ghost.org/docs/config/#mail
    http://blog.ptolemaios.fr/ghost/
------------------------------------------------------------------------------
Ghost was installed successfully! To complete setup of your publication, visit: 
ghost 11:39:32.55 INFO  ==> Configuring Ghost URL to http://blog.ptolemaios.fr
ghost 11:39:32.55 INFO  ==> Passing admin user creation wizard
ghost 11:39:32.56 INFO  ==> Starting Ghost in background
ghost 11:40:34.93 
ghost 11:40:34.94 Welcome to the Bitnami ghost container
ghost 11:40:34.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
ghost 11:40:34.94 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
ghost 11:40:34.94 
ghost 11:40:34.94 INFO  ==> Configuring libnss_wrapper
ghost 11:40:34.96 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 11:40:34.96 INFO  ==> Trying to connect to the database server
ghost 11:40:34.97 DEBUG ==> Executing SQL command:
ghost 11:40:34.98 INFO  ==> Creating database user bn_ghost
ghost 11:40:34.98 DEBUG ==> creating database user \'bn_ghost\'
ghost 11:40:34.98 DEBUG ==> Executing SQL command:
ghost 11:40:35.04 DEBUG ==> Removing all other hosts for the user
ghost 11:40:35.05 DEBUG ==> Executing SQL command:
ghost 11:40:35.07 INFO  ==> Creating database bitnami_ghost
ghost 11:40:35.08 DEBUG ==> Creating database bitnami_ghost
ghost 11:40:35.09 DEBUG ==> Executing SQL command:
ghost 11:40:35.11 DEBUG ==> Providing privileges to username bn_ghost on database bitnami_ghost
ghost 11:40:35.12 DEBUG ==> Executing SQL command:
ghost 11:40:35.22 DEBUG ==> Validating settings in GHOST_* environment variables...
ghost 11:40:35.23 INFO  ==> Ensuring Ghost directories exist
ghost 11:40:35.23 INFO  ==> Trying to connect to the database server
ghost 11:40:35.23 DEBUG ==> Executing SQL command:
ghost 11:40:35.24 INFO  ==> Configuring database
ghost 11:40:35.24 INFO  ==> Setting up Ghost
☱ Inspecting operating system☱ Checking for deprecations☱ Checking for Ghost-CLI updates✔ Configuring Ghost
ghost 11:40:35.85 INFO  ==> Configuring Ghost URL to http://blog.ptolemaios.fr
ghost 11:40:35.86 INFO  ==> Passing admin user creation wizard
```

### Additional information

I'm a real junior in docker/docker-compose, so my docker-compose.yml may have obvious issues that I did not see. But I red all the documentation for both bitnami/ghost and bitnami/mariadb containers so I guess i should not be so far from a good result.
