### ISSUE TITLE
Startup loop after pulling latest (4.46.0) Bitnami/ghost image

### ISSUE THREAD

**Issue by papalouf** [bitnami/bitnami-docker-ghost#126]
### Name and Version

bitnami/ghost:4.46.0

### What steps will reproduce the bug?

- Using docker-compose below, pull latest (4.46.0) bitnami/ghost image.
```
version: '3.8'
services:
  ptolemaios_ghost:
    container_name: ptolemaios_ghost
    image: docker.io/bitnami/ghost:latest
    restart: always
    environment:
      # User/Site configuration
      - GHOST_USERNAME=${GHOST_USERNAME}
      - GHOST_PASSWORD=${GHOST_PASSWORD}
      - GHOST_EMAIL=${GHOST_EMAIL}
      - GHOST_BLOG_TITLE=${GHOST_BLOG_TITLE}
      - GHOST_HOST=${GHOST_HOST}
      # DB connection configuration 
      - GHOST_DATABASE_HOST=ptolemaios_db_ghost
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_NAME=bitnami_ghost
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_PASSWORD=REDACTED
      # Create a database for Ghost using mysql_client
      - BITNAMI_DEBUG=true
    depends_on:
      - ptolemaios_db_ghost
    volumes:
      - /var/www/Ghost_Ptolemaios/bitnami:/bitnami
    networks:
      - backend
      - frontend

  ptolemaios_db_ghost:
    container_name: ptolemaios_db_ghost
    image: bitnami/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=REDACTED
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_general_ci
      - MARIADB_SKIP_TEST_DB=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_PASSWORD=REDACTED
      - MARIADB_DATABASE=bitnami_ghost
      - MARIADB_EXTRA_FLAGS=--max-allowed-packet=1G --innodb-log-file-size=512M --max-connect-errors=10000000 --max_connections=400000
      - BITNAMI_DEBUG=true
    volumes:
      - /var/www/Ghost_Ptolemaios/bitnami:/bitnami
    networks:
      - backend

networks:
  frontend:
    external: false
    name: internal_loop
  backend:
    external: false
    name: ptolemaios_ghost_backend
```

- Container enter in startup loop with debug message 
```
ghost 14:37:15.09 INFO  ==> ** Ghost setup finished! **
ghost 14:37:15.13 INFO  ==> ** Starting Ghost **
- Inspecting operating system
Love open source? We’re hiring Node.js Engineers to work on Ghost full-time.
https://careers.ghost.org/product-engineer-node-js
```

### What is the expected behavior?

Container starting correctly 

### What do you see instead?

Startup loop with debug log below. 

```
ghost 14:41:31.86 
ghost 14:41:31.86 Welcome to the Bitnami ghost container
ghost 14:41:31.86 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
ghost 14:41:31.86 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
ghost 14:41:31.87 
ghost 14:41:31.87 INFO  ==> Configuring libnss_wrapper
ghost 14:41:31.90 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
ghost 14:41:31.94 DEBUG ==> Validating settings in GHOST_* environment variables...
ghost 14:41:31.95 INFO  ==> Restoring persisted Ghost installation
ghost 14:41:32.01 INFO  ==> Trying to connect to the database server
ghost 14:41:32.02 DEBUG ==> Getting database.connection.host from Ghost configuration
ghost 14:41:32.02 DEBUG ==> Getting database.connection.port from Ghost configuration
ghost 14:41:32.03 DEBUG ==> Getting database.connection.database from Ghost configuration
ghost 14:41:32.04 DEBUG ==> Getting database.connection.user from Ghost configuration
ghost 14:41:32.04 DEBUG ==> Getting database.connection.password from Ghost configuration
ghost 14:41:32.05 DEBUG ==> Executing SQL command:
SELECT 1
1
ghost 14:41:32.07 INFO  ==> ** Ghost setup finished! **
ghost 14:41:32.12 INFO  ==> ** Starting Ghost **
- Inspecting operating system
Love open source? We’re hiring Node.js Engineers to work on Ghost full-time.
https://careers.ghost.org/product-engineer-node-js
```

In error log in ./ghost/content/logs folders, I've got this error in last : 

```
{"name":"Log","hostname":"83f2c81ac2f8","pid":105,"level":50,"err":
{"id":400,"domain":"http://blog.ptolemaios.fr","code":"ER_INVALID_DEFAULT","name":"InternalServerError","statusCode":500,"level":"critical","message":"alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'","context":"\"OuterError: alter table `newsletters` modify  `created_at` datetime not null default 'NULL' - Invalid default value for 'created_at'\"","stack":"RollbackError: alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
    at DatabaseStateManager.makeReady (/opt/bitnami/ghost/versions/4.46.0/core/server/data/db/state-manager.js:95:32)
    at RollbackError.KnexMigrateError (/opt/bitnami/ghost/versions/4.46.0/node_modules/knex-migrator/lib/errors.js:7:26)
    at new RollbackError (/opt/bitnami/ghost/versions/4.46.0/node_modules/knex-migrator/lib/errors.js:31:26)
    at KnexMigrator.migrate (/opt/bitnami/ghost/versions/4.46.0/node_modules/knex-migrator/lib/index.js:418:31)
    at async DatabaseStateManager.makeReady (/opt/bitnami/ghost/versions/4.46.0/core/server/data/db/state-manager.js:86:17)
    at async initDatabase (/opt/bitnami/ghost/versions/4.46.0/core/boot.js:69:5)
    at async bootGhost (/opt/bitnami/ghost/versions/4.46.0/core/boot.js:414:9)

Error: alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
    at Packet.asError (/opt/bitnami/ghost/versions/4.46.0/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/opt/bitnami/ghost/versions/4.46.0/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/opt/bitnami/ghost/versions/4.46.0/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/opt/bitnami/ghost/versions/4.46.0/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/opt/bitnami/ghost/versions/4.46.0/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/bitnami/ghost/versions/4.46.0/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","hideStack":false
}
,"msg":"alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'","time":"2022-04-29T13:43:46.074Z","v":0}
```
