### ISSUE TITLE
Listening on 2368 seems hard-coded

### ISSUE THREAD

**Issue by luxas** [bitnami/bitnami-docker-ghost#56]
**Description**

I'm using the [helm chart](https://github.com/kubernetes/charts/tree/master/stable/ghost), and tried to set `ghostPort` to `80`. (I also used ClusterIP and found an other bug which I fixed [here](https://github.com/kubernetes/charts/compare/master...luxas:fix_ghost_clusterip?expand=1))

But although I set `GHOST_PORT_NUMBER` to `"80"` on the ghost container like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k8s-finland-site-ghost
  name: k8s-finland-site-ghost-3859367763-m0p09
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: k8s-finland-site-ghost-3859367763
spec:
  containers:
  - env:
    - name: MARIADB_HOST
      value: k8s-finland-site-mariadb
    - name: MARIADB_PORT_NUMBER
      value: "3306"
    - name: MARIADB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-root-password
          name: k8s-finland-site-mariadb
    - name: GHOST_HOST
      value: kubernetesfinland.com
    - name: GHOST_PORT_NUMBER
      value: "80"
    - name: GHOST_USERNAME
      value: kubernetesfinland
    - name: GHOST_PASSWORD
      valueFrom:
        secretKeyRef:
          key: ghost-password
          name: k8s-finland-site-ghost
    - name: GHOST_EMAIL
    - name: BLOG_TITLE
    - name: SMTP_HOST
    - name: SMTP_PORT
    - name: SMTP_USER
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          key: smtp-password
          name: k8s-finland-site-ghost
    - name: SMTP_SERVICE
    image: bitnami/ghost:0.11.9-r2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 10
      httpGet:
        httpHeaders:
        - name: Host
          value: kubernetesfinland.com
        path: /ghost
        port: http
        scheme: HTTP
      initialDelaySeconds: 200
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: k8s-finland-site-ghost
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 10
      httpGet:
        httpHeaders:
        - name: Host
          value: kubernetesfinland.com
        path: /ghost
        port: http
        scheme: HTTP
      initialDelaySeconds: 100
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 10
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
    volumeMounts:
    - mountPath: /bitnami/ghost
      name: ghost-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-83zfb
      readOnly: true
  volumes:
  - name: ghost-data
    persistentVolumeClaim:
      claimName: k8s-finland-site-ghost
  - name: default-token-83zfb
    secret:
      defaultMode: 420
      secretName: default-token-83zfb
```

**Steps to reproduce the issue:**

1. Set `GHOST_PORT_NUMBER=80`

**Describe the results you received:**

Ghost listens on port 2368

**Describe the results you expected:**

Ghost listens on port 80

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

cc @sebgoa any clue why?
