### ISSUE TITLE
Connection with 'root' user is unsuccessful when connecting to external database

### ISSUE THREAD

**Issue by ritazh** [bitnami/bitnami-docker-ghost#61]
**Description**

Using the latest image `bitnami/ghost:1.17.3-r0`, I'm creating a new ghost chart to deploy Ghost in my k8s cluster. I'm passing in the required env variables for the deployment to connect to an external MySQL database in a secret. But I'm getting the following error from the pod. The secret is created and I see all the keys in the secret. I'm replacing `GHOST_DATABASE_USER` and `MARIADB_ROOT_USER`, not sure why it's still connecting using the `root` user. 

```
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at <redacted_MARIADB_HOST>:<redacted_MARIADB_PORT_NUMBER>
mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
```
`deployment.yml`:

```
{{- if include "ghost.host" . -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ghost.fullname" . }}
  labels:
    app: {{ template "ghost.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "ghost.fullname" . }}
    spec:
      initContainers:
      - name: volume-permissions
        image: "{{ .Values.volumePermissions.image.name }}:{{ .Values.volumePermissions.image.tag }}"
        imagePullPolicy: {{ default "" .Values.volumePermissions.image.pullPolicy | quote }}
        command: ['sh', '-c', 'chmod -R g+rwX /bitnami']
        volumeMounts:
        - mountPath: /bitnami
          name: ghost-data
      containers:
      - name: {{ template "ghost.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: host
        - name: MARIADB_PORT_NUMBER
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: port
        - name: GHOST_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: database
        - name: GHOST_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: username
        - name: GHOST_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: password
        - name: MARIADB_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: username
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}-mysql-secret
              key: password
        - name: GHOST_HOST
          value: {{ include "ghost.host" . | quote }}
        - name: GHOST_PORT_NUMBER
          value: {{ default "80" .Values.ghostPort | quote }}
        - name: GHOST_USERNAME
          value: {{ default "" .Values.ghostUsername | quote }}
        - name: GHOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}
              key: ghost-password
        - name: GHOST_EMAIL
          value: {{ default "" .Values.ghostEmail | quote }}
        - name: BLOG_TITLE
          value: {{ default "" .Values.ghostBlogTitle | quote }}
        - name: SMTP_HOST
          value: {{ default "" .Values.smtpHost | quote }}
        - name: SMTP_PORT
          value: {{ default "" .Values.smtpPort | quote }}
        - name: SMTP_USER
          value: {{ default "" .Values.smtpUser | quote }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "ghost.fullname" . }}
              key: smtp-password
        - name: SMTP_SERVICE
          value: {{ default "" .Values.smtpService | quote }}
        ports:
        - name: http
          containerPort: 2368
        livenessProbe:
          httpGet:
            path: /ghost
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "ghost.host" . | quote }}
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /ghost
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "ghost.host" . | quote }}
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: ghost-data
          mountPath: /bitnami/ghost
      volumes:
      - name: ghost-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "ghost.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end -}}
```
However, using docker-compose, it's working as expected. Here is my `docker-compose.yml`:

```
version: '2'
services:
  ghost:
    image: 'bitnami/ghost:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - MARIADB_HOST=<redacted>
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=<redacted>
      - GHOST_DATABASE_NAME=<redacted>
      - GHOST_DATABASE_PASSWORD=<redacted>
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=localhost
    ports:
      - '80:2368'
    volumes:
      - 'ghost_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
```
This is connecting with the new database user, not `root`. 

**Steps to reproduce the issue:**

This is a bit harder to reproduce as it requires installing the service catalog and service broker. If needed, I can provide the `deployment.yml` and the `secret.yml`.

**Describe the results you received:**

**Describe the results you expected:**

Log from the pod, still using the `root` user to connect.

```
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at <redacted_MARIADB_HOST>:<redacted_MARIADB_PORT_NUMBER>
mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
