### ISSUE TITLE
ghost.log Cannot Open File

### ISSUE THREAD

**Issue by nmyster** [bitnami/bitnami-docker-ghost#65]
Hi,

After playing around with this image and getting it to work how I want, I noticed a bug (maybe?) with how the nami tool creates ghost.log.

It seems to take a file based on the url value in the config or the GHOST_HOST variable which breaks if I want to use a proxy in front of my image as Ghost is listening on 2368 but I receive traffic to my host on 80/443.

The reason I can see for this is that the nami app expects a log file with the 2368 port to be in content/logs, to make this the case, I then end up with homepage links on my blog that have <url>:2368 - which doesn't work due to the proxy being on port 80.

Example:
Passing a URL of `url=http://example.com:2368` results in a content/logs looking like:
```
lrwxrwxrwx 1 1001 root   66 Jan 19 09:52 ghost.log -> 
/opt/bitnami/ghost/logs/http___example_com_2368_production.log
-rw-r--r-- 1 1001 root 2.6K Jan 19 09:52 http___example_com_2368_production.error.log
-rw-r--r-- 1 1001 root  15K Jan 19 09:52 http___example_com_2368_production.log
```
This works but then all links to the site have the port 2368 appended, as explained, doesn't work when the URL is a proxy

If I remove the port from the url:
Example:
`url=http://example.com`

results in
```
lrwxrwxrwx 1 1001 root   66 Jan 19 09:58 ghost.log -> /opt/bitnami/ghost/logs/http___example_com_2368_production.log
-rw-r--r-- 1 1001 root 2.5K Jan 19 09:58 http___example_com_production.error.log
-rw-r--r-- 1 1001 root  15K Jan 19 09:58 http___example_com_production.log
```

This then causes ghost start command in the image to fail as the symlink points to a file that doesn't exist:
```
tail: cannot open '/opt/bitnami/ghost/logs/ghost.log' for reading: No such file or directory
tail: no files remaining
```

Any ideas how to fix this or if this is indeed a bug?

Thanks
Neil

**Comment by nmyster** [comment]
Looking at this https://github.com/TryGhost/Ghost/issues/2598 This is a similar issue where I would just remove the port from url but in this instance, the nami config that creates the ghost.log needs the port

**Comment by tompizmor** [comment]
Hello @nmyster,

I was able to reproduce the issue that you mention. 

As the "url" property in the _config.production.json_ includes the default port (2368), the links to the site have the port 2368 in the URL. That port is configurable via the `GHOST_PORT_NUMBER` environment variable. 

Can you try to deploy Ghost with these env vars and see if it helps?

```
GHOST_HOST=example.com
GHOST_PORT_NUMBER=80
```

**Comment by malko42** [comment]
I ended up having the same problem and adding those 2 lines doesn't help.

**Comment by tompizmor** [comment]
Hi @malko42, I would like to reproduce the issue.

How are you deploying the docker image? docker-compose? helm chart? something else?
Also, which is the exact image version tag that you are using?

**Comment by malko42** [comment]
Hi @tompizmor, sorry for the delay.
I feel dumb now that I have tried and succeeded to deploy it again . I'm using docker-compose and here is an example that looked like what I was using:
```
version: "2"
services:
  faulty_mariadb:
    image: "bitnami/mariadb:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
    volumes:
      - "mariadb_data:/bitnami"
  faulty_ghost:
    image: "bitnami/ghost:1"
    labels:
      kompose.service.type: nodeport
    environment:
      - VIRTUAL_HOST=my.website.me
      - LETSENCRYPT_HOST=my.website.me
      - LETSENCRYPT_EMAIL=my.email@gmail.com
      - MARIADB_HOST=faulty_mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=my.website.me
      - GHOST_PORT_NUMBER=80
      - url=https://my.website.me
    ports:
      - "2368:2368"
    volumes:
      - "ghost_data:/bitnami"
    depends_on:
      - faulty_mariadb
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local

networks:
  default:
    external:
      name: webproxy
```
I may have added `GHOST_PORT_NUMBER` and `GHOST_HOST` but I didn't remove the `url` env variable. And that `url` variable breaks logs as far as I understand.

Since then, I have removed the `url` var and used only `GHOST_PORT_NUMBER` and `GHOST_HOST` and it works as intended. I guess it was once again a case of "not reading the docs enough"

Sorry.
