### ISSUE TITLE
Docker mapped volume, theme folder is empty

### ISSUE THREAD

**Issue by cakirilker** [bitnami/bitnami-docker-ghost#72]
Hello everyone :wave:
Forgive me if it's not right place for the issue that I am having.
I've successfully configured docker container with following compose file:
````yml
blog:
    image: 'bitnami/ghost:latest'
    volumes:
      - '/apps/blog/ghost/data:/bitnami/ghost'
    expose:
      - '2368'
    depends_on:
      - mariadb
    environment:
       ........
````
But when I run following command in mapped directory on my local machine
```{r, engine='bash', count_lines}
ls content/themes
```
I get `casper` output with red color and black background (which means broken link).
However if I exec into container and go to following directory
```{r, engine='bash', count_lines}
ls content/themes
```
I get `casper` output with content in it as expected. 
I used following docker cp command to copy themes folder but no luck, It also copies casper folder as broken link.
```{r, engine='bash', count_lines}
docker cp abd78:/opt/bitnami/ghost/content/themes/casper .
```
I know I can download theme content from ghost admin panel but doesn't bitnami/ghost directory should be mapped to specified directory with all themes and etc. ? 
Thanks,
Ilker
