### ISSUE TITLE
The database migration in Ghost encountered an error.

### ISSUE THREAD

**Issue by gustawdaniel** [bitnami/bitnami-docker-ghost#77]
**Description**

I trying to install some instance of your docker-compose. Now during changing environment variables, I got the error:

```
ghost_1_8f42b04fbbad | Welcome to the Bitnami ghost container
ghost_1_8f42b04fbbad | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
ghost_1_8f42b04fbbad | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
ghost_1_8f42b04fbbad | 
ghost_1_8f42b04fbbad | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
ghost_1_8f42b04fbbad | nami    INFO  Initializing mysql-client
ghost_1_8f42b04fbbad | nami    INFO  mysql-client successfully initialized
ghost_1_8f42b04fbbad | nami    INFO  Initializing ghost
ghost_1_8f42b04fbbad | handler WARN  Using /opt/bitnami/ghost as working directory
ghost_1_8f42b04fbbad | mysql-c INFO  Trying to connect to MySQL server
ghost_1_8f42b04fbbad | mysql-c INFO  Found MySQL server listening at mariadb:3306
ghost_1_8f42b04fbbad | mysql-c INFO  MySQL server listening and working at mariadb:3306
ghost_1_8f42b04fbbad | Error executing 'postInstallation': Message: The database migration in Ghost encountered an error.
ghost_1_8f42b04fbbad | Help: https://docs.ghost.org/faq/upgrade-to-ghost-2-0/#what-to-do-when-an-upgrade-fails
ghost_1_8f42b04fbbad | 
ghost_1_8f42b04fbbad | 
blogprecisesale_ghost_1_8f42b04fbbad exited with code 1
```

**Steps to reproduce the issue:**

1. Prepare two domains connected to one IP - A and B. 
2. Prepare 2 directories A and B.
3. In both directories paste the same docker-compose.yml (version First listed at the end)
4. In A directory docker-compose up, when success you should be able to see your blog
5. In B directory docker-compose up, again everything should work correctly
6. Login as admin by user@example.com and bitnami123 in both blogs and add one post in any blog, and change his name
7. Install docker-compose https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion (instruction at the end) - you can do it as the first step too.
8. Change docker-compose.yml to version with domains (version Second listed at the end)
9. docker-compose up in a catalog A - it should work and you should see your blog connected to a domain
10. docker-compose up in a catalog B - there is an error. Below logs:

**Describe the results you received:**

This is full log:

```
Recreating bloggustawdanielcom_mariadb_1_b9eed77a5e47 ... done
Recreating bloggustawdanielcom_ghost_1_f52aa291b7fa   ... done
Attaching to bloggustawdanielcom_mariadb_1_b9eed77a5e47, bloggustawdanielcom_ghost_1_f52aa291b7fa
mariadb_1_b9eed77a5e47 | 
mariadb_1_b9eed77a5e47 | Welcome to the Bitnami mariadb container
mariadb_1_b9eed77a5e47 | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1_b9eed77a5e47 | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1_b9eed77a5e47 | Send us your feedback at containers@bitnami.com
mariadb_1_b9eed77a5e47 | 
mariadb_1_b9eed77a5e47 | INFO  ==> ** Starting MariaDB setup **
mariadb_1_b9eed77a5e47 | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
mariadb_1_b9eed77a5e47 | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1_b9eed77a5e47 | INFO  ==> Initializing mariadb database...
mariadb_1_b9eed77a5e47 | INFO  ==> Persisted data detected. Restoring...
mariadb_1_b9eed77a5e47 | INFO  ==> Stopping mariadb...
mariadb_1_b9eed77a5e47 | INFO  ==> ** MariaDB setup finished! **
mariadb_1_b9eed77a5e47 | 
mariadb_1_b9eed77a5e47 | INFO  ==> ** Starting MariaDB **
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.37-MariaDB) starting as process 1 ...
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
mariadb_1_b9eed77a5e47 | 
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Using Linux native AIO
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB: Waiting for purge to start
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.41-84.1 started; log sequence number 3057702
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140407518226176 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Warning] 'proxies_priv' entry '@% root@3a402b317337' ignored in --skip-name-resolve mode.
mariadb_1_b9eed77a5e47 | 2019-01-20 23:48:47 140408236152704 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1_b9eed77a5e47 | Version: '10.1.37-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
ghost_1_f52aa291b7fa | 
ghost_1_f52aa291b7fa | Welcome to the Bitnami ghost container
ghost_1_f52aa291b7fa | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
ghost_1_f52aa291b7fa | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
ghost_1_f52aa291b7fa | 
ghost_1_f52aa291b7fa | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
ghost_1_f52aa291b7fa | nami    INFO  Initializing mysql-client
ghost_1_f52aa291b7fa | nami    INFO  mysql-client successfully initialized
ghost_1_f52aa291b7fa | nami    INFO  Initializing ghost
ghost_1_f52aa291b7fa | handler WARN  Using /opt/bitnami/ghost as working directory
ghost_1_f52aa291b7fa | mysql-c INFO  Trying to connect to MySQL server
ghost_1_f52aa291b7fa | mysql-c INFO  Found MySQL server listening at mariadb:3306
ghost_1_f52aa291b7fa | mysql-c INFO  MySQL server listening and working at mariadb:3306
ghost_1_f52aa291b7fa | Error executing 'postInstallation': Message: The database migration in Ghost encountered an error.
ghost_1_f52aa291b7fa | Help: https://docs.ghost.org/faq/upgrade-to-ghost-2-0/#what-to-do-when-an-upgrade-fails
ghost_1_f52aa291b7fa | 
ghost_1_f52aa291b7fa | 
bloggustawdanielcom_ghost_1_f52aa291b7fa exited with code 1
```

**Describe the results you expected:**

I expected that I would see a connection to a domain like in the first instance.

**Additional information you deem important (e.g. issue happens only occasionally):**

We will need .env files in A and B directory with variables:

```
APP_PORT                       - in must be different in A and B
DOMAINS                         - two different domains or subdomains of one domain
LETSENCRYPT_EMAIL   - it can be the same email
NETWORK=webproxy
```

A version of `docker-compose.yml` for IP and PORT (first)

```
version: '3.7'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
    volumes:
      - 'mariadb_data:/bitnami'
  ghost:
    image: 'bitnami/ghost:2'
    labels:
      kompose.service.type: nodeport
    environment:
      - NODE_ENV=production
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=54.37.233.100
      - GHOST_PORT_NUMBER=${APP_PORT}
#      - VIRTUAL_HOST=${DOMAINS}
#      - LETSENCRYPT_HOST=${DOMAINS}
#      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - ${APP_PORT}:2368
    volumes:
      - 'ghost_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local


networks:
  default:
   external:
     name: ${NETWORK}
```

A version of `docker-compose.yml` for SSL DOMAIN (second)

```
version: '3.7'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
    volumes:
      - 'mariadb_data:/bitnami'
  ghost:
    image: 'bitnami/ghost:2'
    labels:
      kompose.service.type: nodeport
    environment:
      - NODE_ENV=production
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=54.37.233.100
      - GHOST_PORT_NUMBER=${APP_PORT}
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - ${APP_PORT}:2368
    volumes:
      - 'ghost_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local


networks:
  default:
   external:
     name: ${NETWORK}
```

How to install https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion?

```
git clone https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion.git
cd docker-compose-letsencrypt-nginx-proxy-companion
mv .env.sample .env
./start.sh
```

**Version**

- Output of `docker version`: 

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 9
 Running: 6
 Paused: 0
 Stopped: 3
Images: 7
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-38-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.9GiB
Name: vps639501
ID: 6BRJ:2PN2:U62M:UFMW:MQSH:FENW:FWC4:Y2SE:COPV:AAL5:D6WV:4HPR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Fresh VPS on OVH. I have similar problems with original repo

> https://hub.docker.com/_/ghost/

and it is described here

> https://github.com/docker-library/ghost/issues/172
