### ISSUE TITLE
https enabled causes broken urls with added port 80 to them

### ISSUE THREAD

**Issue by daniel-farina** [bitnami/bitnami-docker-ghost#78]
**Description**
A fresh installation with a customer docker/compose and 
- GHOST_PROTOCOL=https
will cause the application to load fine but some urls will have broken links such as:

https://site.com:80/tag/getting-started/
The link should be
https://site:80/tag/getting-started/

**Steps to reproduce the issue:**
1. Install with a docker-compose file
2. Enable GHOST_PROTOCOL=https in the docker-compose file.
3. Run
4. Open the website and click on any navigation link

**Version**
- Output of `docker version`:
```
root@auto-94:/home# docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
root@auto-94:/home# docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-50-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 985.5MiB
Name: auto-94
ID: U72H:2RCJ:APMU:HZPO:NY2F:TBL5:CC2H:KA2G:LSHG:UTCQ:KPCA:2JWQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Running on DigitalOcean.

**Comment by daniel-farina** [comment]
so the manual solution to this problem is to edit the configuration file and remove the port 80 from it. 
![image](https://user-images.githubusercontent.com/13665117/59319843-27143a00-8c9a-11e9-8b3e-fb87405b2980.png)

```bash
#Login to your machine
docker exec -it --user root home_ghost_1 bash
#Edit the file and remove port 80 from it
vim config.production.json
exit
```
Then restart your container
```
docker-compose down
docker-compose up -d mariadb
docker-compose up -d ghost
```

I will try to figure out a way of fixing the container automatically.

**Comment by daniel-farina** [comment]
I guess a simpler solution would be to run the following command to set the URL again:

```
docker exec -it home_ghost_1 ghost config url domainname.com
```

**Comment by andresbono** [comment]
Hi @daniel-farina,

Can you execute the following command? It will show the specific version of the Ghost container.

```
docker-compose exec ghost env | grep BITNAMI_IMAGE_VERSION
```

Can you also share with us the content of the `docker-compose.yml` file that you are using?

With that information, we will try to reproduce the issue.

**Comment by daniel-farina** [comment]
hello @andresbono ,

'''
BITNAMI_IMAGE_VERSION=2.23.4-debian-9-r0
'''

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
    volumes:
      - 'mariadb_data:/bitnami'
  ghost:
    image: 'bitnami/ghost:2'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=XXXX.XXXX.com
      - GHOST_USERNAME=XXXXXXX
      - GHOST_PASSWORD=XXXXXXXXXXX
      - GHOST_EMAIL=contact@XXXXXXX.com
      - GHOST_PROTOCOL=https

    ports:
      - '80:2368'
      - '443:443'
    volumes:
      - 'ghost_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
```


Thank you
