### ISSUE TITLE
Error executing 'postInstallation': ENOTSUP

### ISSUE THREAD

**Issue by davidcv5** [bitnami/bitnami-docker-ghost#79]
**Description**

Deploying bitnami/ghost + bitnami/mariadb on Azure Container Instance with mount volume pointing to Azure Storage Account results in the following error:

```shell
Error executing 'postInstallation': ENOTSUP: operation not supported on socket, symlink '/opt/bitnami/ghost/logs' -> '/bitnami/ghost/content/logs'
```

**Steps to reproduce the issue:**

1. Create Azure Storage account with 2 File Shares `mariadb-share` and `ghost-share`
2. Deploy the following Azure Container Group

```yaml
apiVersion: '2018-10-01'
location: eastus
name: ghost-instance
properties:
  containers:
  - name: mariadb
    properties:
      environmentVariables:
      - name: ALLOW_EMPTY_PASSWORD
        value: 'no'
      - name: MARIADB_ROOT_PASSWORD
        value: your-root-password
      image: bitnami/mariadb:10.3
      ports:
      - port: 3306
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 2.0
      volumeMounts:
      - mountPath: /bitnami
        name: mariadb-data
  - name: ghost
    properties:
      environmentVariables:
      - name: MARIADB_HOST
        value: 127.0.0.1
      - name: MARIADB_PORT_NUMBER
        value: '3306'
      - name: ALLOW_EMPTY_PASSWORD
        value: 'no'
      - name: MYSQL_CLIENT_CREATE_DATABASE_USER
        value: bn_ghost
      - name: MYSQL_CLIENT_CREATE_DATABASE_NAME
        value: bitnami_ghost
      - name: MYSQL_CLIENT_CREATE_DATABASE_PASSWORD
        value: ghost-user-password
      - name: MARIADB_ROOT_PASSWORD
        value: your-root-password
      - name: GHOST_DATABASE_NAME
        value: bitnami_ghost
      - name: GHOST_DATABASE_USER
        value: bn_ghost
      - name: GHOST_DATABASE_PASSWORD
        value: ghost-user-password
      - name: GHOST_HOST
        value: your-host
      image: bitnami/ghost:2
      ports:
      - port: 2368
      resources:
        requests:
          cpu: 1
          memoryInGB: 1
      volumeMounts:
      - mountPath: /bitnami
        name: ghost-data
  ipAddress:
    ports:
    - port: 2368
      protocol: TCP
    type: Public
  osType: Linux
  volumes:
  - azureFile:
      shareName: ghost-share
      storageAccountName: your-storage-account
      storageAccountKey: your-key-here
    name: ghost-data
  - azureFile:
      shareName: mariadb-share
      storageAccountName: your-storage-account
      storageAccountKey: your-key-here
    name: mariadb-data
tags: null
type: Microsoft.ContainerInstance/containerGroups
```

**Describe the results you received:**

With the volume mounted, 
```yaml
volumeMounts:
- mountPath: /bitnami
  name: ghost-data 
```
I get the following *error*:
```
Error executing 'postInstallation': ENOTSUP: operation not supported on socket, symlink '/opt/bitnami/ghost/logs' -> '/bitnami/ghost/content/logs'
```

Based on what I understand with symlinks being created, it looks like this:
- contentPath: /opt/bitnami/ghost/content
- link /opt/bitnami/ghost/content -> /bitnami/ghost/content (for persisten purpose)
- link inside content (volume, or in my case azure share) back to image for logs
  /bitnami/ghost/content/logs -> /opt/bitnami/ghost/logs

**Symlink from image to azure share (content) works, but the mapping is from the share to the image (logs) is not supported by azure. I haven't found a way to remove that mapping, is not in the Dockerfile.**

**Describe the results you expected:**

Expect it to work and persist data, but it won't start, fails and the container restarts over and over again. Removing the mount works just fine, but of course then the data is not persisted.
