### ISSUE TITLE
Error executing 'postInstallation': No INPUT matching 'blog-title'

### ISSUE THREAD

**Issue by timmyers** [bitnami/bitnami-docker-ghost#82]
**Description**

Updating to helm chart `8.0.4`  from `7.2.11`, ghost will no longer start up, with the error
`Error executing 'postInstallation': No INPUT matching 'blog-title'`

**Steps to reproduce the issue:**
Helm chart with the following settings:
```javascript
const ghostChart = new k8s.helm.v2.Chart('ghost', {
    repo: 'stable',
    chart: 'ghost',
    version: '8.0.4',
    values: {
      persistence: {
        enabled: false,
      },
      service: {
        type: 'ClusterIP',
      },
      ghostHost: '<domain>',
      ghostUsername: '<username>',
      ghostPassword: process.env.GHOST_ADMIN_PASS,
      mariadb: {
        db: {
          password: 'password',
        },
        rootUser: {
          password: 'password',
        },
      },
      smtpHost: '<smtpHost>',
      smtpUser: '<smtpUser'>,
      smtpPort: '587',
      smtpPassword: process.env.GHOST_SMTP_PASS,
      smtpFromAddress: '<smtpFromAddress>',
      smtpService: '<smtpService>',
    },
  });
```

**Describe the results you received:**

Fails to start up:
```
Welcome to the Bitnami ghost container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at ghost-mariadb:3306
mysql-c INFO  MySQL server listening and working at ghost-mariadb:3306
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...
ghost   INFO  ==> Host configured successfully!
ghost   INFO  ==> Configuring SMTP...
ghost   INFO  ==> Creating admin user...
Error executing 'postInstallation': No INPUT matching 'blog-title'
```

**Comment by carrodher** [comment]
Hi, I think you need to set the `ghostBlogTitle` variable in the same way you are setting `ghostHost`, `ghostUsername`, etc

**Comment by timmyers** [comment]
I have tried setting that but it unfortunately does not seem to make any difference.

**Comment by carrodher** [comment]
Can you share the command (and options) used to upgrade the deployment from `7.2.11` to `8.0.4`?

**Comment by timmyers** [comment]
I just updated the helm chart version with all of the other options staying the same.  This is a part of a pulumi program, but the end result is equivalent to `kubectl apply` of a `helm template` output.

It seems this has something to do with the database. While messing around trying to figure our what's causing this, I brought up a fresh deployment of the helm chart with the new version which worked fine. I then manually deleted the admin user from the database, and then the new deployment has the same behavior of not starting up, giving the `blog-title` error.

I have no idea what could wrong with the original deployment's database though.

**Comment by carrodher** [comment]
Hi, sorry, but I am not able to reproduce the issue.
Those are the steps I did:
- Install the old version of the chart using some passwords and localhost:
```bash
$ helm install stable/ghost --version 7.2.11 --name carlosrh \
--set ghostPassword=r7WTdKixteUP \
--set mariadb.db.password=7UDjBPqK9jMj \
--set mariadb.rootUser.password=mQBwgVwGGZ12 \
--set ghostHost=127.0.0.1 
```
- Check the version and that everything is up and running:
```bash
$ helm list
NAME    	REVISION	UPDATED                 	STATUS  	CHART       	APP VERSION	NAMESPACE
carlosrh	1       	Thu Nov 14 11:31:36 2019	DEPLOYED	ghost-7.2.11	2.37.0     	default

$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
carlosrh-ghost-12df4374d-3c45d   1/1     Running   0          11m
carlosrh-mariadb-0               1/1     Running   0          11m
```
- Upgrade to the latest version using the same parameters:
```bash
$ helm upgrade carlosrh stable/ghost \
--set ghostPassword=r7WTdKixteUP \
--set mariadb.db.password=7UDjBPqK9jMj \
--set mariadb.rootUser.password=mQBwgVwGGZ12 \
--set ghostHost=127.0.0.1
```
- Check the new version and check that everything is up and running after some minutes:
```bash
$ helm list
NAME    	REVISION	UPDATED                 	STATUS  	CHART      	APP VERSION	NAMESPACE
carlosrh	2       	Thu Nov 14 11:34:18 2019	DEPLOYED	ghost-9.0.1	3.0.3      	default

$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
carlosrh-ghost-7ccf8774d-t6wz6   1/1     Running   1          15m
carlosrh-mariadb-0               1/1     Running   0          15m
```
Please, note that it was updated to `9.0.1` instead of `8.0.4` because it is the latest available at this time.

Are you able to reproduce your issue following those upgrade steps?

**Comment by draveness** [comment]
I met the same problem when installing ghost chart with the following values.

```
ghost:
  ghostHost: 127.0.0.1
  ghostUsername: i@draveness.me
  ghostPassword: xxxxx
  ghostEmail: i@draveness.me
  ghostBlogTitle: Title
  service:
    type: ClusterIP
  externalDatabase:
    host: xxx
    port: xxx
    user: xxx
    password: xxx
    database: xxx
  mariadb:
    enabled: false
  ingress:
    enabled: false
  persistence:
    enabled: false
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
```

```
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...
ghost   INFO  ==> Host configured successfully!
ghost   INFO  ==> Creating admin user...
Error executing 'postInstallation': No INPUT matching 'blog-title'
```

**Comment by carrodher** [comment]
I just tried using those new parameters (except the external database ones):
```
helm install stable/ghost --name carlosrh \
--set ghostHost=127.0.0.1 \
--set ghostUsername=i@draveness.me \
--set ghostPassword=petetepetete \
--set ghostEmail=i@draveness.me \
--set ghostBlogTitle=Title \
--set service.type=ClusterIP \
--set ingress.enabled=false \
--set persistence.enabled=false \
--set resources.requests.memory=512Mi \
--set resources.requests.cpu=200m
```
and everything is working fine:
```
kubectl logs -f carlosrh-ghost-55889bb8b5-6sh8h

Welcome to the Bitnami ghost container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at carlosrh-mariadb:3306
mysql-c INFO  MySQL server listening and working at carlosrh-mariadb:3306
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...
ghost   INFO  ==> Host configured successfully!
ghost   INFO  ==> Creating admin user...
ghost   INFO
ghost   INFO  ########################################################################
ghost   INFO   Installation parameters for ghost:
ghost   INFO     Email: i@draveness.me
ghost   INFO     Password: **********
ghost   INFO   (Passwords are not shown for security reasons)
ghost   INFO  ########################################################################
ghost   INFO
nami    INFO  ghost successfully initialized
INFO  ==> Starting ghost...
- Inspecting operating system
[15:34:58] Ensuring user is not logged in as ghost user [started]
[15:34:58] Ensuring user is not logged in as ghost user [skipped]
[15:34:58] Checking if logged in user is directory owner [started]
[15:34:58] Checking if logged in user is directory owner [skipped]
[15:34:58] Checking current folder permissions [started]
[15:34:58] Checking current folder permissions [completed]
[15:34:58] Validating config [started]
[15:34:58] Validating config [completed]
[15:34:58] Checking memory availability [started]
[15:34:58] Checking memory availability [completed]
[15:34:58] Checking binary dependencies [started]
[15:34:58] Checking binary dependencies [completed]
- Starting Ghost: 127-0-0-1
✔ Starting Ghost: 127-0-0-1

------------------------------------------------------------------------------

Your admin interface is located at:

    http://127.0.0.1/ghost/
```

I will continue trying to reproduce the issue in my side to be able to apply some actions to fix it. Maybe it is something related to Helm or k8s versions and that is the reason I am not able to reproduce it. What is your output for the following commands: `helm version` and `kubectl version`?

**Comment by draveness** [comment]
> I will continue trying to reproduce the issue in my side to be able to apply some actions to fix it. Maybe it is something related to Helm or k8s versions and that is the reason I am not able to reproduce it. What is your output for the following commands: helm version and kubectl version?

```go
$ helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```

Could you test it with external database, e.g. create a MySQL database locally, maybe it could help to reproduce the issue. I'm really confused about this..

**Comment by carrodher** [comment]
Can you check if the environment variable `BLOG_TITLE` is set inside the pod/container?
You can do it by running 
```bash
$ kubectl exec -it POD_NAME env | grep -i title
```
where `POD_NAME` is the name of the pod that you can obtain using `kubectl get pods`, the output should be something like:
```bash
$ kubectl get pods
NAME                              READY   STATUS             RESTARTS   AGE
carlosrh-ghost-55889bb8b5-gmlnr   1/1     Running            1          23m
carlosrh-mariadb-0                1/1     Running            0          23m

$ kubectl exec -it carlosrh-ghost-55889bb8b5-gmlnr env | grep -i title
BLOG_TITLE=Title
```

**Comment by draveness** [comment]
```go
kubectl exec -it metal-ghost-66dfc497cf-rfth7 env | grep -i title
BLOG_TITLE=面向信仰编程
```

**Comment by carrodher** [comment]
Is this the output when you deployed the chart with the above parameters? I mean, some messages ago you mentioned that you're deploying the chart using those values:
```yaml
ghost:
  ghostHost: 127.0.0.1
  ghostUsername: i@draveness.me
  ghostPassword: xxxxx
  ghostEmail: i@draveness.me
  ghostBlogTitle: Title
...
```
where `ghostBlogTitle` is "Title". In the last commands, the `BLOG_TITLE ` environment variable is set to "面向信仰编程" while it should be the same value.

**Comment by draveness** [comment]
It is the same value, I changed the title to 'Title' when first posted here.

Regards, Draven

**Comment by carrodher** [comment]
Hi, there is some news about the issue (although I am not able to reproduce the issue).
The image has some logic to detect if there are data from previous Ghost installations or not, if there are existing data, the initialization is not started and the new installation uses the previous data.

In your case, it seems that it is trying to create the admin user again but it is not possible (the wizard doesn't appear). Are you removing the volumes? Can you take a look at the volumes?

In this screenshot from [diffchecker](https://www.diffchecker.com/5vUJEmvj) you can see in the left side the log after the first installation (there are some actions like creating admin user, configuring the database, etc); in the right side those items don't appear and there is a message about restoring data:
![Screen Shot 2019-11-26 at 12 25 57](https://user-images.githubusercontent.com/13216600/69626084-33256580-1048-11ea-8039-bb1bc289e7fd.png)

It seems, in your case, even during the upgrade process the logs are showing the first installation logs:
```
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...
ghost   INFO  ==> Host configured successfully!
ghost   INFO  ==> Creating admin user...
```
Those actions shouldn't happen if the volume is attached properly. Can you take a look at the volumes configuration?

**Comment by draveness** [comment]
> Those actions shouldn't happen if the volume is attached properly. Can you take a look at the volumes configuration?

Do I have to enable `persistence` is the values.yml?

**Comment by carrodher** [comment]
Yes, to upgrade the application some data should be persisted.
 In the persistent volume is included the `config.production.json` file and the `content` directory.

**Comment by draveness** [comment]
> Yes, to upgrade the application some data should be persisted.
> In the persistent volume is included the `config.production.json` file and the `content` directory.

Why not store the data in MySQL? Add another PVC seems redundant and makes migration more tricky.

**Comment by draveness** [comment]
> Yes, to upgrade the application some data should be persisted.
> In the persistent volume is included the `config.production.json` file and the `content` directory.

I enable the persistence in values.yaml and meet the same problem..

**Comment by draveness** [comment]
I deleted the database and solved the problem, but I don't think it is the right approach for this.

**Comment by draveness** [comment]
I have managed to reproduce the issue, with disabled persistence and external database. Drop the external database and create a new one first.

1. Install the chart, and we'll get the happy result.

ghost   INFO  ########################################################################
ghost   INFO   Installation parameters for ghost:
ghost   INFO     Email: i@draveness.me
ghost   INFO     Password: **********
ghost   INFO   (Passwords are not shown for security reasons)
ghost   INFO  ########################################################################
ghost   INFO

2. Delete the ghost pod, and the container can't be able to restart

```
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   INFO  ==> Configuring host...
ghost   INFO  ==> Restarting service...
ghost   INFO  ==> Host configured successfully!
ghost   INFO  ==> Creating admin user...
Error executing 'postInstallation': No INPUT matching 'blog-title'
```

**Comment by carrodher** [comment]
Hi, some web applications store files, configuration, images, static files, etc in some directories. This data can't be moved to the database that is the reason why we're using a PVC to store this kind of data

**Comment by draveness** [comment]
But if I delete the PVC accidentally, I can’t restart the service any more because of this error. If it is designed on purpose, it would make more sense to give a clear error rather than the blog title error. And we could get the blog title from the database......

Regards,
Draven

**Comment by carrodher** [comment]
I agree with the verbosity, we should add a proper error message. I just created a task for this purpose.

There is a workaround to skip the first initialization if you accidentally remove the PVC. You can create an empty _.initialized_ file in the persisted directory (_/bitnami/ghost_), in this way the post-installation logic will assume the application is already initialized and it wouldn't execute the initialization logic; but as I mentioned before, as there are some static files, configuration, etc stored in the PVC I am not sure if the upgrade will work without those files.

**Comment by draveness** [comment]
> There is a workaround to skip the first initialization if you accidentally remove the PVC. You can create an empty .initialized file in the persisted directory (/bitnami/ghost), in this way the post-installation logic will assume the application is already initialized and it wouldn't execute the initialization logic; but as I mentioned before, as there are some static files, configuration, etc stored in the PVC I am not sure if the upgrade will work without those files.

Thanks for doing this, it would be great to have this feature!

**Comment by saikatharryc** [comment]
Even I'm facing the same error related to the blog title, just after creating an admin user step.
I'm passing like this:
`ghostBlogTitle: "My blog" `
in the other hand, just to let you know that, I'm unable to attach persisted volume, so I have made it false,
```
persistence:
  enabled: false
```
is PV is necessary? is the error I'm facing because of that?

**Comment by carrodher** [comment]
Can you share your whole `docker-compose.yaml`? I will try to reproduce the issue using the same configuration

**Comment by saikatharryc** [comment]
@carrodher I'm trying with Helm chart: https://github.com/helm/charts/tree/master/stable/ghost

**Comment by juan131** [comment]
Hi @saikatharryc 

I was unable to reproduce the issue. These are the steps I followed:

```console
$ helm install stable/ghost --name my-release --set ghostBlogTitle="New Blog Title" --set service.type=ClusterIP 
$ kubectl port-forward --namespace default svc/my-release-ghost 8080:80 &
$ curl -sL http://127.0.0.1:8080/ | grep "<title>"
    <title>New Blog Title</title>
```

As you can see the title of the blog has been adapted to what I set when installing the chart.

**Comment by matthewmodestino** [comment]
I was able to replicate this today on fresh install on Microk8s latest



```
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

## Bitnami Ghost image version
## ref: https://hub.docker.com/r/bitnami/ghost/tags/
##
image:
  registry: docker.io
  repository: bitnami/ghost
  tag: 3.1.1-debian-9-r0
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## String to partially override ghost.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override ghost.fullname template
##
# fullnameOverride:

## Init containers parameters:
## volumePermissions: Change the owner of the persist volume mountpoint to RunAsUser:fsGroup
##
volumePermissions:
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: stretch
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

## Ghost protocol, host, port and path to create application URLs
## ref: https://github.com/bitnami/bitnami-docker-ghost#configuration
##
ghostProtocol: http
ghostHost: foo.io 
ghostPort: 2368
ghostPath: /

## User of the application
## ref: https://github.com/bitnami/bitnami-docker-ghost#configuration
##
ghostUsername: admin

## Application password
## Defaults to a random 10-character alphanumeric string if not set
## ref: https://github.com/bitnami/bitnami-docker-ghost#configuration
##
ghostPassword: h3llow0rld

## Admin email
## ref: https://github.com/bitnami/bitnami-docker-ghost#configuration
##
ghostEmail: admin@foo.io

## Ghost Blog name
## ref: https://github.com/bitnami/bitnami-docker-ghost#environment-variables
##
ghostBlogTitle: foo.io 

## Set to `yes` to allow the container to be started with blank passwords
## ref: https://github.com/bitnami/bitnami-docker-wordpress#environment-variables
allowEmptyPassword: no

## SMTP mail delivery configuration
## ref: https://github.com/bitnami/bitnami-docker-redmine/#smtp-configuration
##
# smtpHost:
# smtpPort:
# smtpUser:
# smtpPassword:
# smtpFromAddress
# smtpService:

##
## External database configuration
##
externalDatabase:
  ## All of these values are only used when mariadb.enabled is set to false
  ## Database host
  host: localhost

  ## non-root Username for Wordpress Database
  user: bn_ghost

  ## Database password
  password: ""

  ## Database name
  database: bitnami_ghost

  ## Database port number
  port: 3306

##
## MariaDB chart configuration
##
## https://github.com/helm/charts/blob/master/stable/mariadb/values.yaml
##
mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Disable MariaDB replication
  replication:
    enabled: false

  ## Create a database and a database user
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-user-on-first-run
  ##
  db:
    name: bitnami_ghost
    user: bn_ghost
    ## If the password is not specified, mariadb will generates a random password
    ##
    password: h3llow0rld

  ## MariaDB admin password
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  rootUser:
    password: h3llow0rld

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  master:
    persistence:
      enabled: true
      ## mariadb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 8Gi

## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
##
service:
  type: NodePort 
  # HTTP Port
  port: 2368
  ## loadBalancerIP:
  ##
  ## nodePorts:
  ##   http: <to set explicitly, choose port between 30000-32767>
  nodePorts:
    http: ""
  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  ## Service annotations done as key:value pairs
  annotations:

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  ## ghost data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi
  path: /bitnami

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 300m

## Configure the ingress resource that allows you to access the
## Ghost installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  ## Set to true to enable ingress record generation
  enabled: false

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: false

  ## Ingress annotations done as key:value pairs
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations:
  #  kubernetes.io/ingress.class: nginx

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: foo.io
    path: /

    ## Set this to true in order to enable TLS on the ingress record
    tls: false

    ## Optionally specify the TLS hosts for the ingress record
    ## Useful when the Ingress controller supports www-redirection
    ## If not specified, the above host name will be used
    # tlsHosts:
    # - www.ghost.local
    # - ghost.local

    ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
    tlsSecret: ghost.local-tls

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: ghost.local-tls
  #   key:
  #   certificate:

## Node selector for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
##
nodeSelector: {}

## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}
```


I am running hostpath provisioner for the PVC. MariaDB is coming up no problem. 




```
NAME                    READY   STATUS             RESTARTS   AGE
ghost-b8747f78f-4vm6v   0/1     CrashLoopBackOff   14         58m
ghost-mariadb-0         1/1     Running            0          58m
```

```
kubectl -n ghost describe pod ghost-b8747f78f-4vm6v
Name:         ghost-b8747f78f-4vm6v
Namespace:    ghost
Priority:     0
Node:         lab/192.168.2.183
Start Time:   Mon, 06 Jan 2020 23:59:14 +0000
Labels:       app=ghost
              chart=ghost-9.0.4
              pod-template-hash=b8747f78f
              release=ghost
Annotations:  <none>
Status:       Running
IP:           10.1.74.41
IPs:
  IP:           10.1.74.41
Controlled By:  ReplicaSet/ghost-b8747f78f
Containers:
  ghost:
    Container ID:   containerd://777f61e1ceac758cd3c06585f9213475d0f757c31038210c84476bce5966416f
    Image:          docker.io/bitnami/ghost:3.1.1-debian-9-r0
    Image ID:       docker.io/bitnami/ghost@sha256:0aefb35cf4e03b6f8586faf27158c14f17f1be142891d1607d94214e813b4ac3
    Port:           2368/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 07 Jan 2020 00:58:28 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 07 Jan 2020 00:52:56 +0000
      Finished:     Tue, 07 Jan 2020 00:53:21 +0000
    Ready:          False
    Restart Count:  15
    Requests:
      cpu:      300m
      memory:   512Mi
    Liveness:   http-get http://:http/ delay=120s timeout=5s period=10s #success=1 #failure=6
    Readiness:  http-get http://:http/ delay=30s timeout=3s period=5s #success=1 #failure=3
    Environment:
      ALLOW_EMPTY_PASSWORD:     no
      MARIADB_HOST:             ghost-mariadb
      MARIADB_PORT_NUMBER:      3306
      GHOST_DATABASE_NAME:      bitnami_ghost
      GHOST_DATABASE_USER:      bn_ghost
      GHOST_DATABASE_PASSWORD:  <set to the key 'mariadb-password' in secret 'ghost-mariadb'>  Optional: false
      GHOST_HOST:               foo.io/
      GHOST_PROTOCOL:           http
      GHOST_PORT_NUMBER:        2368
      GHOST_USERNAME:           admin
      GHOST_PASSWORD:           <set to the key 'ghost-password' in secret 'ghost'>  Optional: false
      GHOST_EMAIL:              admin@foo.io
      BLOG_TITLE:               foo.io
    Mounts:
      /bitnami/ghost from ghost-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-k9k82 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ghost-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  ghost
    ReadOnly:   false
  default-token-k9k82:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-k9k82
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  59m                   default-scheduler  Successfully assigned ghost/ghost-b8747f78f-4vm6v to lab
  Warning  Unhealthy  58m (x9 over 58m)     kubelet, lab       Readiness probe failed: Get http://10.1.74.41:2368/: dial tcp 10.1.74.41:2368: connect: connection refused
  Warning  Unhealthy  57m (x3 over 58m)     kubelet, lab       Readiness probe failed: HTTP probe failed with statuscode: 404
  Normal   Created    57m (x3 over 59m)     kubelet, lab       Created container ghost
  Normal   Started    57m (x3 over 59m)     kubelet, lab       Started container ghost
  Normal   Pulled     39m (x9 over 59m)     kubelet, lab       Container image "docker.io/bitnami/ghost:3.1.1-debian-9-r0" already present on machine
  Warning  BackOff    4m9s (x228 over 57m)  kubelet, lab       Back-off restarting failed container

```
