### ISSUE TITLE
is there any way to use S3 with ghost helm chart

### ISSUE THREAD

**Issue by saikatharryc** [bitnami/bitnami-docker-ghost#84]
Instead of using volume, is there any way to manage or pass s3 vars in values?
https://ghost.org/integrations/amazon-s3/

**Comment by dani8art** [comment]
Hi @saikatharryc ,

Just a quick note to let you know we are evaluating and checking this issue and we will let you know as soon as we have more information.

Thanks

**Comment by saikatharryc** [comment]
@dani8art @carrodher  any idea on how can we pass or make use of storage adapters using `bitnami/ghost:3.1.1`?

This is using  [ghost](https://hub.docker.com/_/ghost/) image
```
FROM ghost:3.1.1
COPY ./config.production.json config.production.json
USER root
RUN ls && npm install ghost-storage-adapter-s3 -S 
RUN mkdir -p ./content.orig/adapters/storage
RUN cp -r ./node_modules/ghost-storage-adapter-s3 ./content.orig/adapters/storage/s3
```

if using [bitnami/ghost](https://hub.docker.com/r/bitnami/ghost/), how do we build the image? to make use of This adapter settings commands.?
any input on this?

**Comment by dani8art** [comment]
Hi @saikatharryc ,

Currently, we do not support any command or input by default, however, I was trying a solution using `FROM` statement and I found an approach that could fit your requirements.

As we use non-root container we need to be root for install some packages and modify the `app-entrypoint.sh`, then, we should come back to the non-root user and we can install the storage adapter. We also added some environment variables to configure the adapter so that we avoid to add credentials in the docker image.

#### Dockerfile
```
FROM bitnami/ghost:latest

USER root

RUN install_packages jq
RUN mkdir -p /.npm && chmod -R g+rwX,o+rw /.npm

COPY post_ghost_config.sh /
RUN chmod +x /post_ghost_config.sh \
    && cp /app-entrypoint.sh /tmp/app-entrypoint.sh \
    && sed '/info "Starting ghost... "/ a . /post_ghost_config.sh' /tmp/app-entrypoint.sh > /app-entrypoint.sh 

ENV AWS_ACCESS_KEY_ID="AWS_ACCESS_KEY_ID" \
    AWS_ACCESS_SECRET_KEY="AWS_ACCESS_SECRET_KEY" \
    AWS_REGION="AWS_REGION" \
    AWS_BUCKET="AWS_BUCKET" 

USER 1001

RUN cd /bitnami/ghost \
    && npm i --silent ghost-storage-adapter-s3 \ 
    && mkdir -p /bitnami/ghost/content/adapters/storage/s3 \
    && cp -r ./node_modules/ghost-storage-adapter-s3/* /bitnami/ghost/content/adapters/storage/s3/ 
```

As you probably know,  we configure the ghost instance while the container is starting and we use some environment variables to do that, then, If you want to add configuration you should do after our configuration is done. Because of that, we are adding this script to our `app-entrypoint.sh`, otherwise, you will override the `config.production.json`. 

#### post_ghost_config.sh
```shell
#!/bin/bash -e
cp /bitnami/ghost/config.production.json /tmp/config.tmp.json

jq -r --arg keyId $AWS_ACCESS_KEY_ID --arg accessKey $AWS_ACCESS_SECRET_KEY --arg region $AWS_REGION --arg bucket $AWS_BUCKET \
    '. + { storage: { active: "s3", s3: { accessKeyId: $keyId, secretAccessKey: $accessKey, region: $region, bucket: $bucket } } }' \
    /tmp/config.tmp.json > /bitnami/ghost/config.production.json
```

Then, you can build your image and use it like:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
    volumes:
      - 'mariadb_data:/bitnami'
  ghost:
    image: '<your_image_tag>'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=localhost
      - AWS_ACCESS_KEY_ID=<your_access_key_id>
      - AWS_ACCESS_SECRET_KEY=<your_access_secret_key>
      - AWS_REGION=<your_aws_region>
      - AWS_BUCKET=<your_s3_bucket>
    ports:
      - '80:2368'
    volumes:
      - 'ghost_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
```

I hope this approach fits you, let us know if you have any problem.

Regards.
