### ISSUE TITLE
[HELM] No pods showing up

### ISSUE THREAD

**Issue by Jacob1r** [bitnami/bitnami-docker-ghost#91]
**Description**
I am using the helm chart to try and deploy the blog to my cluster.
I have deployed other helm charts so it is not an issue with helm.
The service and ingress get deployed fine, but no pod shows up for me.
I am using gitlab for deployment.

**Steps to reproduce the issue:**

$GHOST_VERSION = v10.1.14

1. - if [ "$DEPLOY_TYPE" == "install" ]; then helm upgrade --install --version $GHOST_VERSION example-blog bitnami/ghost -n example --create-namespace -f values.yml --set ghostPassword=$EXAMPLE_BLOG_PASSWORD --set externalDatabase.password=$EXAMPLE_DATABASE_PASSWORD --set smtpPassword=$EXAMPLE_SMTP_PASSWORD; fi

**Describe the results you received:**
When I do this to test to see what should be deployed I don't see a deployment file:
`helm template g bitnami/ghost -f ./values.yml --debug---`
Here is the result:
```
# Source: ghost/templates/secrets-external-db.yaml
apiVersion: v1
kind: Secret
metadata:
  name: g-ghost-external-db
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-10.1.12
    app.kubernetes.io/instance: g
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
...
# Source: ghost/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: g-ghost
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-10.1.12
    app.kubernetes.io/instance: g
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  ghost-password: "example"
...
# Source: ghost/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: g-ghost
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-10.1.12
    app.kubernetes.io/instance: g
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
...
# Source: ghost/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: g-ghost
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-10.1.12
    app.kubernetes.io/instance: g
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  loadBalancerIP: ""
  ports:
    - name: http
      port: 80
      targetPort: http
  selector: 
    app.kubernetes.io/name: ghost
    app.kubernetes.io/instance: g
...
# Source: ghost/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: g-ghost
  labels:
    app.kubernetes.io/name: ghost
    helm.sh/chart: ghost-10.1.12
    app.kubernetes.io/instance: g
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: blog.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: g-ghost
              servicePort: http
  tls:
    - hosts:
      - blog.example.com
      secretName: example-ghost.local-tls

```

Here is the HELM value file:

```

## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass

## Bitnami Ghost image version
## ref: https://hub.docker.com/r/bitnami/ghost/tags/
##
image:
  registry: docker.io
  repository: bitnami/ghost
  tag: 3.33.0-debian-10-r6
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## String to partially override ghost.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override ghost.fullname template
##
# fullnameOverride:

## Init containers parameters:
## volumePermissions: Change the owner of the persist volume mountpoint to RunAsUser:fsGroup
##
volumePermissions:
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

## Ghost protocol, host, port and path to create application URLs
## ref: https://github.com/bitnami/bitnami-docker-ghost#configuration
##
ghostProtocol: https
# ghostHost:
ghostPort: 443
ghostPath: /

## User of the application
## ref: https://github.com/bitnami/bitnami-docker-ghost#configuration
##
ghostUsername: example

## Application password
## Defaults to a random 10-character alphanumeric string if not set
## ref: https://github.com/bitnami/bitnami-docker-ghost#configuration
##
# ghostPassword: example

## Admin email
## ref: https://github.com/bitnami/bitnami-docker-ghost#configuration
##
ghostEmail: example@example.com

## Ghost Blog name
## ref: https://github.com/bitnami/bitnami-docker-ghost#environment-variables
##
ghostBlogTitle: example

## Set to `true` to allow the container to be started with blank passwords
## ref: https://github.com/bitnami/bitnami-docker-wordpress#environment-variables
allowEmptyPassword: false

## SMTP mail delivery configuration
## ref: https://github.com/bitnami/bitnami-docker-redmine/#smtp-configuration
##
smtpHost: example
smtpPort: example
smtpUser: example
smtpPassword: example
smtpFromAddress: example
smtpService: example

## Use an existing secrets which already store your password data
##
# existingSecret:
#   ## Name of the existing secret
#   ##
#   name: mySecret
#   ## Key mapping where <key> is the value which the deployment is expecting and
#   ## <value> is the name of the key in the existing secret.
#   ##
#   keyMapping:
#     ghost-password: myGhostPasswordKey
#     smtp-password: mySmtpPasswordKey

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
##
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1

##
## External database configuration
##
externalDatabase:
  ## All of these values are only used when mariadb.enabled is set to false
  ## Database host
  host: mariadb

  ## non-root Username for Wordpress Database
  user: example

  ## Database password
  password: "example"

  ## Database name
  database: example_blog

  ## Database port number
  port: 3306

##
## MariaDB chart configuration
##
## https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml
##
mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: false
  ## Disable MariaDB replication
  replication:
    enabled: false

  ## Create a database and a database user
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-user-on-first-run
  ##
  db:
    name: bitnami_ghost
    user: bn_ghost
    ## If the password is not specified, mariadb will generates a random password
    ##
    # password: example

  ## MariaDB admin password
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  # rootUser:
  #   password:

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  master:
    persistence:
      enabled: true
      ## mariadb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 8Gi

## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
##
service:
  type: LoadBalancer

  ## HTTP Port
  port: 80

  ## Extra ports to expose (normally used with the `sidecar` value)
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services
  ##
  extraPorts: []

  ## Specify the loadBalancerIP value for LoadBalancer service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
  ##
  loadBalancerIP:

  ## nodePorts:
  ##   http: <to set explicitly, choose port between 30000-32767>
  nodePorts:
    http: ""

  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster

  ## Service annotations. Evaluated as a template
  ##
  annotations: {}

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  ## ghost data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi
  path: /bitnami

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 512Mi
    cpu: 300m

## Configure the ingress resource that allows you to access the
## Ghost installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## Set this to true in order to add the corresponding annotations for cert-manager
  certManager: true

  ## Ingress annotations. Evaluated as a template.
  ## For a full list of possible ingress annotations, please see
  ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
  ##
  ## If tls is set to true, annotation ingress.kubernetes.io/secure-backends: "true" will automatically be set
  ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
  annotations:
  #  kubernetes.io/ingress.class: nginx
     kubernetes.io/ingress.class: traefik

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
    - name: blog.example.com
      path: /

      ## Set this to true in order to enable TLS on the ingress record
      tls: true

      ## Optionally specify the TLS hosts for the ingress record
      ## Useful when the Ingress controller supports www-redirection
      ## If not specified, the above host name will be used
      # tlsHosts:
      # - www.ghost.local
      # - ghost.local

      ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
      tlsSecret: example-ghost.local-tls

  secrets:
  ## If you're providing your own certificates, please use this to add the certificates as secrets
  ## key and certificate should start with -----BEGIN CERTIFICATE----- or
  ## -----BEGIN RSA PRIVATE KEY-----
  ##
  ## name should line up with a tlsSecret set further up
  ## If you're using cert-manager, this is unneeded, as it will create the secret for you if it is not set
  ##
  ## It is also possible to create and manage the certificates outside of this helm chart
  ## Please see README.md for more information
  # - name: ghost.local-tls
  #   key:
  #   certificate:

## Node selector for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
##
nodeSelector: {}

## Affinity for pod assignment (evaluated as a template)
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Additional pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## Add sidecars to the pod
## For example:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
sidecars: []

## Add init containers to the pod
## For example:
## initContainers:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##
initContainers: []

## Array to add extra volumes
##
extraVolumes: []

## Array to add extra mounts (normally used with extraVolumes)
##
extraVolumeMounts: []

## An array to add extra env vars
## For example:
## extraEnvVars:
##  - name: MY_ENV_VAR
##    value: env_var_value
##
extraEnvVars: []

## Name of a ConfigMap containing extra env vars
##
extraEnvVarsConfigMap:

## Name of a Secret containing extra env vars
##
extraEnvVarsSecret:

```

when I do:
**kubectl get svc -A**
```
NAMESPACE       NAME                       TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)                      AGE
example   example-blog-ghost   LoadBalancer   10.245.220.8     external-ip   80:31292/TCP                 9m18s
```

**kubectl get ingress -A**
```
NAMESPACE       NAME                       CLASS    HOSTS                            ADDRESS   PORTS     AGE
example   example-blog-ghost   <none>   blog.example.com             80, 443   10m
```

**Version**
kubectl: 1.9
helm: 3.3.0
ghost helm chart version: v10.1.14
